"""empty message

Revision ID: c28b1c9f7cad
Revises: 10a795c73ed0
Create Date: 2021-12-11 08:24:51.292662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c28b1c9f7cad'
down_revision = '10a795c73ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
